package com.github.diogocerqueiralima.domain.devices.repositories

import com.github.diogocerqueiralima.domain.devices.model.Device
import java.util.UUID

/**
 * Repository interface for managing Device entities.
 */
interface DeviceRepository {

    /**
     * Finds a Device by its unique identifier.
     *
     * @param id The unique identifier of the Device.
     * @return The Device if found, or null if no Device with the given ID exists.
     */
    suspend fun findById(id: UUID): Device?

    /**
     * @return A list of all Devices available in the repository.
     */
    suspend fun findAll(): List<Device>

    /**
     * Creates or updates a Device identified by [id], owned by the given user.
     *
     * @param id Unique identifier of the device, generated by the device itself.
     * @param serialNumber Manufacturer-assigned serial number of the device.
     * @param model Model name of the device.
     * @param manufacturer Manufacturer of the device.
     * @param imei International Mobile Equipment Identity of the device.
     * @param ownerId Identifier of the user who owns the device.
     * @return The created or updated Device.
     */
    suspend fun createOrUpdate(id: UUID, serialNumber: String, model: String, manufacturer: String, imei: String, ownerId: UUID): Device

}
