syntax = "proto3";

package com.github.diogocerqueiralima.schema.proto;

import "google/protobuf/timestamp.proto";

option java_multiple_files = true;

service DeviceService {

  rpc GetDeviceById(DeviceId) returns (DeviceResponse);
  rpc DeviceIsOwnedByUser(DeviceIsOwnedByUserRequest) returns (DeviceIsOwnedByUserResponse);

}

message DeviceIsOwnedByUserRequest {

  string device_id = 1;
  string user_id = 2;

}

message DeviceIsOwnedByUserResponse {

  bool is_owned = 1;

}

message DeviceId {

  string id = 1;

}

message DeviceResponse {

  string id = 1;
  string owner_id = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
  string serial_number = 5;
  string model = 6;
  string manufacturer = 7;
  string imei = 8;

}
