// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vehicle-tracker-schemas/Location.proto
// Protobuf Java Version: 4.33.1

package location;

@com.google.protobuf.Generated
public final class LocationOuterClass extends com.google.protobuf.GeneratedFile {
  private LocationOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "LocationOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code location.Hemisphere}
   */
  public enum Hemisphere
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <code>NORTH = 1;</code>
     */
    NORTH(1),
    /**
     * <code>SOUTH = 2;</code>
     */
    SOUTH(2),
    /**
     * <code>EAST = 3;</code>
     */
    EAST(3),
    /**
     * <code>WEST = 4;</code>
     */
    WEST(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "Hemisphere");
    }
    /**
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <code>NORTH = 1;</code>
     */
    public static final int NORTH_VALUE = 1;
    /**
     * <code>SOUTH = 2;</code>
     */
    public static final int SOUTH_VALUE = 2;
    /**
     * <code>EAST = 3;</code>
     */
    public static final int EAST_VALUE = 3;
    /**
     * <code>WEST = 4;</code>
     */
    public static final int WEST_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Hemisphere valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Hemisphere forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return NORTH;
        case 2: return SOUTH;
        case 3: return EAST;
        case 4: return WEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Hemisphere>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Hemisphere> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Hemisphere>() {
            public Hemisphere findValueByNumber(int number) {
              return Hemisphere.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return location.LocationOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Hemisphere[] VALUES = values();

    public static Hemisphere valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Hemisphere(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:location.Hemisphere)
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:location.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string latitude = 3;</code>
     * @return The latitude.
     */
    java.lang.String getLatitude();
    /**
     * <code>string latitude = 3;</code>
     * @return The bytes for latitude.
     */
    com.google.protobuf.ByteString
        getLatitudeBytes();

    /**
     * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
     * @return The enum numeric value on the wire for latitudeHemisphere.
     */
    int getLatitudeHemisphereValue();
    /**
     * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
     * @return The latitudeHemisphere.
     */
    location.LocationOuterClass.Hemisphere getLatitudeHemisphere();

    /**
     * <code>string longitude = 5;</code>
     * @return The longitude.
     */
    java.lang.String getLongitude();
    /**
     * <code>string longitude = 5;</code>
     * @return The bytes for longitude.
     */
    com.google.protobuf.ByteString
        getLongitudeBytes();

    /**
     * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
     * @return The enum numeric value on the wire for longitudeHemisphere.
     */
    int getLongitudeHemisphereValue();
    /**
     * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
     * @return The longitudeHemisphere.
     */
    location.LocationOuterClass.Hemisphere getLongitudeHemisphere();

    /**
     * <code>float altitude = 7;</code>
     * @return The altitude.
     */
    float getAltitude();

    /**
     * <code>float speed = 8;</code>
     * @return The speed.
     */
    float getSpeed();

    /**
     * <code>float heading = 9;</code>
     * @return The heading.
     */
    float getHeading();

    /**
     * <code>uint32 mode = 10;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <code>uint32 satellite_type = 11;</code>
     * @return The satelliteType.
     */
    int getSatelliteType();

    /**
     * <code>uint32 fix_status = 12;</code>
     * @return The fixStatus.
     */
    int getFixStatus();

    /**
     * <code>uint32 satellites_used = 13;</code>
     * @return The satellitesUsed.
     */
    int getSatellitesUsed();

    /**
     * <code>double time = 14;</code>
     * @return The time.
     */
    double getTime();

    /**
     * <code>uint32 date = 15;</code>
     * @return The date.
     */
    int getDate();

    /**
     * <code>float hdop = 16;</code>
     * @return The hdop.
     */
    float getHdop();

    /**
     * <code>float pdop = 17;</code>
     * @return The pdop.
     */
    float getPdop();

    /**
     * <code>float vdop = 18;</code>
     * @return The vdop.
     */
    float getVdop();
  }
  /**
   * Protobuf type {@code location.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:location.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "Location");
    }
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      latitude_ = "";
      latitudeHemisphere_ = 0;
      longitude_ = "";
      longitudeHemisphere_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return location.LocationOuterClass.internal_static_location_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return location.LocationOuterClass.internal_static_location_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              location.LocationOuterClass.Location.class, location.LocationOuterClass.Location.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object latitude_ = "";
    /**
     * <code>string latitude = 3;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latitude_ = s;
        return s;
      }
    }
    /**
     * <code>string latitude = 3;</code>
     * @return The bytes for latitude.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_HEMISPHERE_FIELD_NUMBER = 4;
    private int latitudeHemisphere_ = 0;
    /**
     * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
     * @return The enum numeric value on the wire for latitudeHemisphere.
     */
    @java.lang.Override public int getLatitudeHemisphereValue() {
      return latitudeHemisphere_;
    }
    /**
     * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
     * @return The latitudeHemisphere.
     */
    @java.lang.Override public location.LocationOuterClass.Hemisphere getLatitudeHemisphere() {
      location.LocationOuterClass.Hemisphere result = location.LocationOuterClass.Hemisphere.forNumber(latitudeHemisphere_);
      return result == null ? location.LocationOuterClass.Hemisphere.UNRECOGNIZED : result;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object longitude_ = "";
    /**
     * <code>string longitude = 5;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitude_ = s;
        return s;
      }
    }
    /**
     * <code>string longitude = 5;</code>
     * @return The bytes for longitude.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_HEMISPHERE_FIELD_NUMBER = 6;
    private int longitudeHemisphere_ = 0;
    /**
     * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
     * @return The enum numeric value on the wire for longitudeHemisphere.
     */
    @java.lang.Override public int getLongitudeHemisphereValue() {
      return longitudeHemisphere_;
    }
    /**
     * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
     * @return The longitudeHemisphere.
     */
    @java.lang.Override public location.LocationOuterClass.Hemisphere getLongitudeHemisphere() {
      location.LocationOuterClass.Hemisphere result = location.LocationOuterClass.Hemisphere.forNumber(longitudeHemisphere_);
      return result == null ? location.LocationOuterClass.Hemisphere.UNRECOGNIZED : result;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 7;
    private float altitude_ = 0F;
    /**
     * <code>float altitude = 7;</code>
     * @return The altitude.
     */
    @java.lang.Override
    public float getAltitude() {
      return altitude_;
    }

    public static final int SPEED_FIELD_NUMBER = 8;
    private float speed_ = 0F;
    /**
     * <code>float speed = 8;</code>
     * @return The speed.
     */
    @java.lang.Override
    public float getSpeed() {
      return speed_;
    }

    public static final int HEADING_FIELD_NUMBER = 9;
    private float heading_ = 0F;
    /**
     * <code>float heading = 9;</code>
     * @return The heading.
     */
    @java.lang.Override
    public float getHeading() {
      return heading_;
    }

    public static final int MODE_FIELD_NUMBER = 10;
    private int mode_ = 0;
    /**
     * <code>uint32 mode = 10;</code>
     * @return The mode.
     */
    @java.lang.Override
    public int getMode() {
      return mode_;
    }

    public static final int SATELLITE_TYPE_FIELD_NUMBER = 11;
    private int satelliteType_ = 0;
    /**
     * <code>uint32 satellite_type = 11;</code>
     * @return The satelliteType.
     */
    @java.lang.Override
    public int getSatelliteType() {
      return satelliteType_;
    }

    public static final int FIX_STATUS_FIELD_NUMBER = 12;
    private int fixStatus_ = 0;
    /**
     * <code>uint32 fix_status = 12;</code>
     * @return The fixStatus.
     */
    @java.lang.Override
    public int getFixStatus() {
      return fixStatus_;
    }

    public static final int SATELLITES_USED_FIELD_NUMBER = 13;
    private int satellitesUsed_ = 0;
    /**
     * <code>uint32 satellites_used = 13;</code>
     * @return The satellitesUsed.
     */
    @java.lang.Override
    public int getSatellitesUsed() {
      return satellitesUsed_;
    }

    public static final int TIME_FIELD_NUMBER = 14;
    private double time_ = 0D;
    /**
     * <code>double time = 14;</code>
     * @return The time.
     */
    @java.lang.Override
    public double getTime() {
      return time_;
    }

    public static final int DATE_FIELD_NUMBER = 15;
    private int date_ = 0;
    /**
     * <code>uint32 date = 15;</code>
     * @return The date.
     */
    @java.lang.Override
    public int getDate() {
      return date_;
    }

    public static final int HDOP_FIELD_NUMBER = 16;
    private float hdop_ = 0F;
    /**
     * <code>float hdop = 16;</code>
     * @return The hdop.
     */
    @java.lang.Override
    public float getHdop() {
      return hdop_;
    }

    public static final int PDOP_FIELD_NUMBER = 17;
    private float pdop_ = 0F;
    /**
     * <code>float pdop = 17;</code>
     * @return The pdop.
     */
    @java.lang.Override
    public float getPdop() {
      return pdop_;
    }

    public static final int VDOP_FIELD_NUMBER = 18;
    private float vdop_ = 0F;
    /**
     * <code>float vdop = 18;</code>
     * @return The vdop.
     */
    @java.lang.Override
    public float getVdop() {
      return vdop_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(latitude_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, latitude_);
      }
      if (latitudeHemisphere_ != location.LocationOuterClass.Hemisphere.UNDEFINED.getNumber()) {
        output.writeEnum(4, latitudeHemisphere_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(longitude_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, longitude_);
      }
      if (longitudeHemisphere_ != location.LocationOuterClass.Hemisphere.UNDEFINED.getNumber()) {
        output.writeEnum(6, longitudeHemisphere_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        output.writeFloat(7, altitude_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        output.writeFloat(8, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(heading_) != 0) {
        output.writeFloat(9, heading_);
      }
      if (mode_ != 0) {
        output.writeUInt32(10, mode_);
      }
      if (satelliteType_ != 0) {
        output.writeUInt32(11, satelliteType_);
      }
      if (fixStatus_ != 0) {
        output.writeUInt32(12, fixStatus_);
      }
      if (satellitesUsed_ != 0) {
        output.writeUInt32(13, satellitesUsed_);
      }
      if (java.lang.Double.doubleToRawLongBits(time_) != 0) {
        output.writeDouble(14, time_);
      }
      if (date_ != 0) {
        output.writeUInt32(15, date_);
      }
      if (java.lang.Float.floatToRawIntBits(hdop_) != 0) {
        output.writeFloat(16, hdop_);
      }
      if (java.lang.Float.floatToRawIntBits(pdop_) != 0) {
        output.writeFloat(17, pdop_);
      }
      if (java.lang.Float.floatToRawIntBits(vdop_) != 0) {
        output.writeFloat(18, vdop_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(latitude_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, latitude_);
      }
      if (latitudeHemisphere_ != location.LocationOuterClass.Hemisphere.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, latitudeHemisphere_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(longitude_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, longitude_);
      }
      if (longitudeHemisphere_ != location.LocationOuterClass.Hemisphere.UNDEFINED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, longitudeHemisphere_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, altitude_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(heading_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, heading_);
      }
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, mode_);
      }
      if (satelliteType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, satelliteType_);
      }
      if (fixStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, fixStatus_);
      }
      if (satellitesUsed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, satellitesUsed_);
      }
      if (java.lang.Double.doubleToRawLongBits(time_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, time_);
      }
      if (date_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, date_);
      }
      if (java.lang.Float.floatToRawIntBits(hdop_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(16, hdop_);
      }
      if (java.lang.Float.floatToRawIntBits(pdop_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(17, pdop_);
      }
      if (java.lang.Float.floatToRawIntBits(vdop_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(18, vdop_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof location.LocationOuterClass.Location)) {
        return super.equals(obj);
      }
      location.LocationOuterClass.Location other = (location.LocationOuterClass.Location) obj;

      if (!getLatitude()
          .equals(other.getLatitude())) return false;
      if (latitudeHemisphere_ != other.latitudeHemisphere_) return false;
      if (!getLongitude()
          .equals(other.getLongitude())) return false;
      if (longitudeHemisphere_ != other.longitudeHemisphere_) return false;
      if (java.lang.Float.floatToIntBits(getAltitude())
          != java.lang.Float.floatToIntBits(
              other.getAltitude())) return false;
      if (java.lang.Float.floatToIntBits(getSpeed())
          != java.lang.Float.floatToIntBits(
              other.getSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getHeading())
          != java.lang.Float.floatToIntBits(
              other.getHeading())) return false;
      if (getMode()
          != other.getMode()) return false;
      if (getSatelliteType()
          != other.getSatelliteType()) return false;
      if (getFixStatus()
          != other.getFixStatus()) return false;
      if (getSatellitesUsed()
          != other.getSatellitesUsed()) return false;
      if (java.lang.Double.doubleToLongBits(getTime())
          != java.lang.Double.doubleToLongBits(
              other.getTime())) return false;
      if (getDate()
          != other.getDate()) return false;
      if (java.lang.Float.floatToIntBits(getHdop())
          != java.lang.Float.floatToIntBits(
              other.getHdop())) return false;
      if (java.lang.Float.floatToIntBits(getPdop())
          != java.lang.Float.floatToIntBits(
              other.getPdop())) return false;
      if (java.lang.Float.floatToIntBits(getVdop())
          != java.lang.Float.floatToIntBits(
              other.getVdop())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude().hashCode();
      hash = (37 * hash) + LATITUDE_HEMISPHERE_FIELD_NUMBER;
      hash = (53 * hash) + latitudeHemisphere_;
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude().hashCode();
      hash = (37 * hash) + LONGITUDE_HEMISPHERE_FIELD_NUMBER;
      hash = (53 * hash) + longitudeHemisphere_;
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAltitude());
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeading());
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode();
      hash = (37 * hash) + SATELLITE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSatelliteType();
      hash = (37 * hash) + FIX_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getFixStatus();
      hash = (37 * hash) + SATELLITES_USED_FIELD_NUMBER;
      hash = (53 * hash) + getSatellitesUsed();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate();
      hash = (37 * hash) + HDOP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHdop());
      hash = (37 * hash) + PDOP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPdop());
      hash = (37 * hash) + VDOP_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVdop());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static location.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static location.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static location.LocationOuterClass.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static location.LocationOuterClass.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static location.LocationOuterClass.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static location.LocationOuterClass.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static location.LocationOuterClass.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static location.LocationOuterClass.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(location.LocationOuterClass.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code location.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:location.Location)
        location.LocationOuterClass.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return location.LocationOuterClass.internal_static_location_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return location.LocationOuterClass.internal_static_location_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                location.LocationOuterClass.Location.class, location.LocationOuterClass.Location.Builder.class);
      }

      // Construct using location.LocationOuterClass.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        latitude_ = "";
        latitudeHemisphere_ = 0;
        longitude_ = "";
        longitudeHemisphere_ = 0;
        altitude_ = 0F;
        speed_ = 0F;
        heading_ = 0F;
        mode_ = 0;
        satelliteType_ = 0;
        fixStatus_ = 0;
        satellitesUsed_ = 0;
        time_ = 0D;
        date_ = 0;
        hdop_ = 0F;
        pdop_ = 0F;
        vdop_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return location.LocationOuterClass.internal_static_location_Location_descriptor;
      }

      @java.lang.Override
      public location.LocationOuterClass.Location getDefaultInstanceForType() {
        return location.LocationOuterClass.Location.getDefaultInstance();
      }

      @java.lang.Override
      public location.LocationOuterClass.Location build() {
        location.LocationOuterClass.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public location.LocationOuterClass.Location buildPartial() {
        location.LocationOuterClass.Location result = new location.LocationOuterClass.Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(location.LocationOuterClass.Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.latitudeHemisphere_ = latitudeHemisphere_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.longitude_ = longitude_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.longitudeHemisphere_ = longitudeHemisphere_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.altitude_ = altitude_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.heading_ = heading_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.mode_ = mode_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.satelliteType_ = satelliteType_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.fixStatus_ = fixStatus_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.satellitesUsed_ = satellitesUsed_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.time_ = time_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.date_ = date_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.hdop_ = hdop_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.pdop_ = pdop_;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.vdop_ = vdop_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof location.LocationOuterClass.Location) {
          return mergeFrom((location.LocationOuterClass.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(location.LocationOuterClass.Location other) {
        if (other == location.LocationOuterClass.Location.getDefaultInstance()) return this;
        if (!other.getLatitude().isEmpty()) {
          latitude_ = other.latitude_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.latitudeHemisphere_ != 0) {
          setLatitudeHemisphereValue(other.getLatitudeHemisphereValue());
        }
        if (!other.getLongitude().isEmpty()) {
          longitude_ = other.longitude_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.longitudeHemisphere_ != 0) {
          setLongitudeHemisphereValue(other.getLongitudeHemisphereValue());
        }
        if (java.lang.Float.floatToRawIntBits(other.getAltitude()) != 0) {
          setAltitude(other.getAltitude());
        }
        if (java.lang.Float.floatToRawIntBits(other.getSpeed()) != 0) {
          setSpeed(other.getSpeed());
        }
        if (java.lang.Float.floatToRawIntBits(other.getHeading()) != 0) {
          setHeading(other.getHeading());
        }
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        if (other.getSatelliteType() != 0) {
          setSatelliteType(other.getSatelliteType());
        }
        if (other.getFixStatus() != 0) {
          setFixStatus(other.getFixStatus());
        }
        if (other.getSatellitesUsed() != 0) {
          setSatellitesUsed(other.getSatellitesUsed());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getTime()) != 0) {
          setTime(other.getTime());
        }
        if (other.getDate() != 0) {
          setDate(other.getDate());
        }
        if (java.lang.Float.floatToRawIntBits(other.getHdop()) != 0) {
          setHdop(other.getHdop());
        }
        if (java.lang.Float.floatToRawIntBits(other.getPdop()) != 0) {
          setPdop(other.getPdop());
        }
        if (java.lang.Float.floatToRawIntBits(other.getVdop()) != 0) {
          setVdop(other.getVdop());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 26: {
                latitude_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 26
              case 32: {
                latitudeHemisphere_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 32
              case 42: {
                longitude_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 42
              case 48: {
                longitudeHemisphere_ = input.readEnum();
                bitField0_ |= 0x00000008;
                break;
              } // case 48
              case 61: {
                altitude_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 61
              case 69: {
                speed_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 69
              case 77: {
                heading_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 77
              case 80: {
                mode_ = input.readUInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 80
              case 88: {
                satelliteType_ = input.readUInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 88
              case 96: {
                fixStatus_ = input.readUInt32();
                bitField0_ |= 0x00000200;
                break;
              } // case 96
              case 104: {
                satellitesUsed_ = input.readUInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 104
              case 113: {
                time_ = input.readDouble();
                bitField0_ |= 0x00000800;
                break;
              } // case 113
              case 120: {
                date_ = input.readUInt32();
                bitField0_ |= 0x00001000;
                break;
              } // case 120
              case 133: {
                hdop_ = input.readFloat();
                bitField0_ |= 0x00002000;
                break;
              } // case 133
              case 141: {
                pdop_ = input.readFloat();
                bitField0_ |= 0x00004000;
                break;
              } // case 141
              case 149: {
                vdop_ = input.readFloat();
                bitField0_ |= 0x00008000;
                break;
              } // case 149
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object latitude_ = "";
      /**
       * <code>string latitude = 3;</code>
       * @return The latitude.
       */
      public java.lang.String getLatitude() {
        java.lang.Object ref = latitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string latitude = 3;</code>
       * @return The bytes for latitude.
       */
      public com.google.protobuf.ByteString
          getLatitudeBytes() {
        java.lang.Object ref = latitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string latitude = 3;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        latitude_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        latitude_ = getDefaultInstance().getLatitude();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string latitude = 3;</code>
       * @param value The bytes for latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        latitude_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int latitudeHemisphere_ = 0;
      /**
       * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
       * @return The enum numeric value on the wire for latitudeHemisphere.
       */
      @java.lang.Override public int getLatitudeHemisphereValue() {
        return latitudeHemisphere_;
      }
      /**
       * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
       * @param value The enum numeric value on the wire for latitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLatitudeHemisphereValue(int value) {
        latitudeHemisphere_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
       * @return The latitudeHemisphere.
       */
      @java.lang.Override
      public location.LocationOuterClass.Hemisphere getLatitudeHemisphere() {
        location.LocationOuterClass.Hemisphere result = location.LocationOuterClass.Hemisphere.forNumber(latitudeHemisphere_);
        return result == null ? location.LocationOuterClass.Hemisphere.UNRECOGNIZED : result;
      }
      /**
       * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
       * @param value The latitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLatitudeHemisphere(location.LocationOuterClass.Hemisphere value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        latitudeHemisphere_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.location.Hemisphere latitude_hemisphere = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitudeHemisphere() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitudeHemisphere_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object longitude_ = "";
      /**
       * <code>string longitude = 5;</code>
       * @return The longitude.
       */
      public java.lang.String getLongitude() {
        java.lang.Object ref = longitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string longitude = 5;</code>
       * @return The bytes for longitude.
       */
      public com.google.protobuf.ByteString
          getLongitudeBytes() {
        java.lang.Object ref = longitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string longitude = 5;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        longitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string longitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        longitude_ = getDefaultInstance().getLongitude();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string longitude = 5;</code>
       * @param value The bytes for longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        longitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int longitudeHemisphere_ = 0;
      /**
       * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
       * @return The enum numeric value on the wire for longitudeHemisphere.
       */
      @java.lang.Override public int getLongitudeHemisphereValue() {
        return longitudeHemisphere_;
      }
      /**
       * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
       * @param value The enum numeric value on the wire for longitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLongitudeHemisphereValue(int value) {
        longitudeHemisphere_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
       * @return The longitudeHemisphere.
       */
      @java.lang.Override
      public location.LocationOuterClass.Hemisphere getLongitudeHemisphere() {
        location.LocationOuterClass.Hemisphere result = location.LocationOuterClass.Hemisphere.forNumber(longitudeHemisphere_);
        return result == null ? location.LocationOuterClass.Hemisphere.UNRECOGNIZED : result;
      }
      /**
       * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
       * @param value The longitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLongitudeHemisphere(location.LocationOuterClass.Hemisphere value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000008;
        longitudeHemisphere_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.location.Hemisphere longitude_hemisphere = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitudeHemisphere() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitudeHemisphere_ = 0;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <code>float altitude = 7;</code>
       * @return The altitude.
       */
      @java.lang.Override
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <code>float altitude = 7;</code>
       * @param value The altitude to set.
       * @return This builder for chaining.
       */
      public Builder setAltitude(float value) {

        altitude_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>float altitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        altitude_ = 0F;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>float speed = 8;</code>
       * @return The speed.
       */
      @java.lang.Override
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>float speed = 8;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float speed = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private float heading_ ;
      /**
       * <code>float heading = 9;</code>
       * @return The heading.
       */
      @java.lang.Override
      public float getHeading() {
        return heading_;
      }
      /**
       * <code>float heading = 9;</code>
       * @param value The heading to set.
       * @return This builder for chaining.
       */
      public Builder setHeading(float value) {

        heading_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>float heading = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000040);
        heading_ = 0F;
        onChanged();
        return this;
      }

      private int mode_ ;
      /**
       * <code>uint32 mode = 10;</code>
       * @return The mode.
       */
      @java.lang.Override
      public int getMode() {
        return mode_;
      }
      /**
       * <code>uint32 mode = 10;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {

        mode_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 mode = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        mode_ = 0;
        onChanged();
        return this;
      }

      private int satelliteType_ ;
      /**
       * <code>uint32 satellite_type = 11;</code>
       * @return The satelliteType.
       */
      @java.lang.Override
      public int getSatelliteType() {
        return satelliteType_;
      }
      /**
       * <code>uint32 satellite_type = 11;</code>
       * @param value The satelliteType to set.
       * @return This builder for chaining.
       */
      public Builder setSatelliteType(int value) {

        satelliteType_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 satellite_type = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearSatelliteType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        satelliteType_ = 0;
        onChanged();
        return this;
      }

      private int fixStatus_ ;
      /**
       * <code>uint32 fix_status = 12;</code>
       * @return The fixStatus.
       */
      @java.lang.Override
      public int getFixStatus() {
        return fixStatus_;
      }
      /**
       * <code>uint32 fix_status = 12;</code>
       * @param value The fixStatus to set.
       * @return This builder for chaining.
       */
      public Builder setFixStatus(int value) {

        fixStatus_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fix_status = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearFixStatus() {
        bitField0_ = (bitField0_ & ~0x00000200);
        fixStatus_ = 0;
        onChanged();
        return this;
      }

      private int satellitesUsed_ ;
      /**
       * <code>uint32 satellites_used = 13;</code>
       * @return The satellitesUsed.
       */
      @java.lang.Override
      public int getSatellitesUsed() {
        return satellitesUsed_;
      }
      /**
       * <code>uint32 satellites_used = 13;</code>
       * @param value The satellitesUsed to set.
       * @return This builder for chaining.
       */
      public Builder setSatellitesUsed(int value) {

        satellitesUsed_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 satellites_used = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearSatellitesUsed() {
        bitField0_ = (bitField0_ & ~0x00000400);
        satellitesUsed_ = 0;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>double time = 14;</code>
       * @return The time.
       */
      @java.lang.Override
      public double getTime() {
        return time_;
      }
      /**
       * <code>double time = 14;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(double value) {

        time_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>double time = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000800);
        time_ = 0D;
        onChanged();
        return this;
      }

      private int date_ ;
      /**
       * <code>uint32 date = 15;</code>
       * @return The date.
       */
      @java.lang.Override
      public int getDate() {
        return date_;
      }
      /**
       * <code>uint32 date = 15;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(int value) {

        date_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 date = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00001000);
        date_ = 0;
        onChanged();
        return this;
      }

      private float hdop_ ;
      /**
       * <code>float hdop = 16;</code>
       * @return The hdop.
       */
      @java.lang.Override
      public float getHdop() {
        return hdop_;
      }
      /**
       * <code>float hdop = 16;</code>
       * @param value The hdop to set.
       * @return This builder for chaining.
       */
      public Builder setHdop(float value) {

        hdop_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>float hdop = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearHdop() {
        bitField0_ = (bitField0_ & ~0x00002000);
        hdop_ = 0F;
        onChanged();
        return this;
      }

      private float pdop_ ;
      /**
       * <code>float pdop = 17;</code>
       * @return The pdop.
       */
      @java.lang.Override
      public float getPdop() {
        return pdop_;
      }
      /**
       * <code>float pdop = 17;</code>
       * @param value The pdop to set.
       * @return This builder for chaining.
       */
      public Builder setPdop(float value) {

        pdop_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>float pdop = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearPdop() {
        bitField0_ = (bitField0_ & ~0x00004000);
        pdop_ = 0F;
        onChanged();
        return this;
      }

      private float vdop_ ;
      /**
       * <code>float vdop = 18;</code>
       * @return The vdop.
       */
      @java.lang.Override
      public float getVdop() {
        return vdop_;
      }
      /**
       * <code>float vdop = 18;</code>
       * @param value The vdop to set.
       * @return This builder for chaining.
       */
      public Builder setVdop(float value) {

        vdop_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <code>float vdop = 18;</code>
       * @return This builder for chaining.
       */
      public Builder clearVdop() {
        bitField0_ = (bitField0_ & ~0x00008000);
        vdop_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:location.Location)
    }

    // @@protoc_insertion_point(class_scope:location.Location)
    private static final location.LocationOuterClass.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new location.LocationOuterClass.Location();
    }

    public static location.LocationOuterClass.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public location.LocationOuterClass.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_location_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_location_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&vehicle-tracker-schemas/Location.proto" +
      "\022\010location\"\341\002\n\010Location\022\020\n\010latitude\030\003 \001(" +
      "\t\0221\n\023latitude_hemisphere\030\004 \001(\0162\024.locatio" +
      "n.Hemisphere\022\021\n\tlongitude\030\005 \001(\t\0222\n\024longi" +
      "tude_hemisphere\030\006 \001(\0162\024.location.Hemisph" +
      "ere\022\020\n\010altitude\030\007 \001(\002\022\r\n\005speed\030\010 \001(\002\022\017\n\007" +
      "heading\030\t \001(\002\022\014\n\004mode\030\n \001(\r\022\026\n\016satellite" +
      "_type\030\013 \001(\r\022\022\n\nfix_status\030\014 \001(\r\022\027\n\017satel" +
      "lites_used\030\r \001(\r\022\014\n\004time\030\016 \001(\001\022\014\n\004date\030\017" +
      " \001(\r\022\014\n\004hdop\030\020 \001(\002\022\014\n\004pdop\030\021 \001(\002\022\014\n\004vdop" +
      "\030\022 \001(\002*E\n\nHemisphere\022\r\n\tUNDEFINED\020\000\022\t\n\005N" +
      "ORTH\020\001\022\t\n\005SOUTH\020\002\022\010\n\004EAST\020\003\022\010\n\004WEST\020\004b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_location_Location_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_location_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_location_Location_descriptor,
        new java.lang.String[] { "Latitude", "LatitudeHemisphere", "Longitude", "LongitudeHemisphere", "Altitude", "Speed", "Heading", "Mode", "SatelliteType", "FixStatus", "SatellitesUsed", "Time", "Date", "Hdop", "Pdop", "Vdop", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
