// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vehicle-tracker-schemas/Telemetry.proto
// Protobuf Java Version: 4.32.1

package schemas.v1.telemetry;

@com.google.protobuf.Generated
public final class Telemetry extends com.google.protobuf.GeneratedFile {
  private Telemetry() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      Telemetry.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceTelemetryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schemas.v1.telemetry.DeviceTelemetry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>int64 uptime = 2;</code>
     * @return The uptime.
     */
    long getUptime();

    /**
     * <code>float battery_percentage = 3;</code>
     * @return The batteryPercentage.
     */
    float getBatteryPercentage();

    /**
     * <code>double cpu_usage = 4;</code>
     * @return The cpuUsage.
     */
    double getCpuUsage();

    /**
     * <code>double memory_usage = 5;</code>
     * @return The memoryUsage.
     */
    double getMemoryUsage();

    /**
     * <code>double disk_usage = 6;</code>
     * @return The diskUsage.
     */
    double getDiskUsage();

    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     * @return Whether the networkTelemetry field is set.
     */
    boolean hasNetworkTelemetry();
    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     * @return The networkTelemetry.
     */
    schemas.v1.telemetry.Telemetry.NetworkTelemetry getNetworkTelemetry();
    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     */
    schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder getNetworkTelemetryOrBuilder();
  }
  /**
   * Protobuf type {@code schemas.v1.telemetry.DeviceTelemetry}
   */
  public static final class DeviceTelemetry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:schemas.v1.telemetry.DeviceTelemetry)
      DeviceTelemetryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        DeviceTelemetry.class.getName());
    }
    // Use DeviceTelemetry.newBuilder() to construct.
    private DeviceTelemetry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DeviceTelemetry() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_DeviceTelemetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schemas.v1.telemetry.Telemetry.DeviceTelemetry.class, schemas.v1.telemetry.Telemetry.DeviceTelemetry.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int UPTIME_FIELD_NUMBER = 2;
    private long uptime_ = 0L;
    /**
     * <code>int64 uptime = 2;</code>
     * @return The uptime.
     */
    @java.lang.Override
    public long getUptime() {
      return uptime_;
    }

    public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 3;
    private float batteryPercentage_ = 0F;
    /**
     * <code>float battery_percentage = 3;</code>
     * @return The batteryPercentage.
     */
    @java.lang.Override
    public float getBatteryPercentage() {
      return batteryPercentage_;
    }

    public static final int CPU_USAGE_FIELD_NUMBER = 4;
    private double cpuUsage_ = 0D;
    /**
     * <code>double cpu_usage = 4;</code>
     * @return The cpuUsage.
     */
    @java.lang.Override
    public double getCpuUsage() {
      return cpuUsage_;
    }

    public static final int MEMORY_USAGE_FIELD_NUMBER = 5;
    private double memoryUsage_ = 0D;
    /**
     * <code>double memory_usage = 5;</code>
     * @return The memoryUsage.
     */
    @java.lang.Override
    public double getMemoryUsage() {
      return memoryUsage_;
    }

    public static final int DISK_USAGE_FIELD_NUMBER = 6;
    private double diskUsage_ = 0D;
    /**
     * <code>double disk_usage = 6;</code>
     * @return The diskUsage.
     */
    @java.lang.Override
    public double getDiskUsage() {
      return diskUsage_;
    }

    public static final int NETWORK_TELEMETRY_FIELD_NUMBER = 7;
    private schemas.v1.telemetry.Telemetry.NetworkTelemetry networkTelemetry_;
    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     * @return Whether the networkTelemetry field is set.
     */
    @java.lang.Override
    public boolean hasNetworkTelemetry() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     * @return The networkTelemetry.
     */
    @java.lang.Override
    public schemas.v1.telemetry.Telemetry.NetworkTelemetry getNetworkTelemetry() {
      return networkTelemetry_ == null ? schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance() : networkTelemetry_;
    }
    /**
     * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
     */
    @java.lang.Override
    public schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder getNetworkTelemetryOrBuilder() {
      return networkTelemetry_ == null ? schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance() : networkTelemetry_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (uptime_ != 0L) {
        output.writeInt64(2, uptime_);
      }
      if (java.lang.Float.floatToRawIntBits(batteryPercentage_) != 0) {
        output.writeFloat(3, batteryPercentage_);
      }
      if (java.lang.Double.doubleToRawLongBits(cpuUsage_) != 0) {
        output.writeDouble(4, cpuUsage_);
      }
      if (java.lang.Double.doubleToRawLongBits(memoryUsage_) != 0) {
        output.writeDouble(5, memoryUsage_);
      }
      if (java.lang.Double.doubleToRawLongBits(diskUsage_) != 0) {
        output.writeDouble(6, diskUsage_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(7, getNetworkTelemetry());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (uptime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uptime_);
      }
      if (java.lang.Float.floatToRawIntBits(batteryPercentage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, batteryPercentage_);
      }
      if (java.lang.Double.doubleToRawLongBits(cpuUsage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, cpuUsage_);
      }
      if (java.lang.Double.doubleToRawLongBits(memoryUsage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, memoryUsage_);
      }
      if (java.lang.Double.doubleToRawLongBits(diskUsage_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, diskUsage_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getNetworkTelemetry());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof schemas.v1.telemetry.Telemetry.DeviceTelemetry)) {
        return super.equals(obj);
      }
      schemas.v1.telemetry.Telemetry.DeviceTelemetry other = (schemas.v1.telemetry.Telemetry.DeviceTelemetry) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getUptime()
          != other.getUptime()) return false;
      if (java.lang.Float.floatToIntBits(getBatteryPercentage())
          != java.lang.Float.floatToIntBits(
              other.getBatteryPercentage())) return false;
      if (java.lang.Double.doubleToLongBits(getCpuUsage())
          != java.lang.Double.doubleToLongBits(
              other.getCpuUsage())) return false;
      if (java.lang.Double.doubleToLongBits(getMemoryUsage())
          != java.lang.Double.doubleToLongBits(
              other.getMemoryUsage())) return false;
      if (java.lang.Double.doubleToLongBits(getDiskUsage())
          != java.lang.Double.doubleToLongBits(
              other.getDiskUsage())) return false;
      if (hasNetworkTelemetry() != other.hasNetworkTelemetry()) return false;
      if (hasNetworkTelemetry()) {
        if (!getNetworkTelemetry()
            .equals(other.getNetworkTelemetry())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + UPTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUptime());
      hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBatteryPercentage());
      hash = (37 * hash) + CPU_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getCpuUsage()));
      hash = (37 * hash) + MEMORY_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMemoryUsage()));
      hash = (37 * hash) + DISK_USAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDiskUsage()));
      if (hasNetworkTelemetry()) {
        hash = (37 * hash) + NETWORK_TELEMETRY_FIELD_NUMBER;
        hash = (53 * hash) + getNetworkTelemetry().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(schemas.v1.telemetry.Telemetry.DeviceTelemetry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code schemas.v1.telemetry.DeviceTelemetry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:schemas.v1.telemetry.DeviceTelemetry)
        schemas.v1.telemetry.Telemetry.DeviceTelemetryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_DeviceTelemetry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                schemas.v1.telemetry.Telemetry.DeviceTelemetry.class, schemas.v1.telemetry.Telemetry.DeviceTelemetry.Builder.class);
      }

      // Construct using schemas.v1.telemetry.Telemetry.DeviceTelemetry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetNetworkTelemetryFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        uptime_ = 0L;
        batteryPercentage_ = 0F;
        cpuUsage_ = 0D;
        memoryUsage_ = 0D;
        diskUsage_ = 0D;
        networkTelemetry_ = null;
        if (networkTelemetryBuilder_ != null) {
          networkTelemetryBuilder_.dispose();
          networkTelemetryBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor;
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.DeviceTelemetry getDefaultInstanceForType() {
        return schemas.v1.telemetry.Telemetry.DeviceTelemetry.getDefaultInstance();
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.DeviceTelemetry build() {
        schemas.v1.telemetry.Telemetry.DeviceTelemetry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.DeviceTelemetry buildPartial() {
        schemas.v1.telemetry.Telemetry.DeviceTelemetry result = new schemas.v1.telemetry.Telemetry.DeviceTelemetry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(schemas.v1.telemetry.Telemetry.DeviceTelemetry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uptime_ = uptime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.batteryPercentage_ = batteryPercentage_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cpuUsage_ = cpuUsage_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.memoryUsage_ = memoryUsage_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.diskUsage_ = diskUsage_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.networkTelemetry_ = networkTelemetryBuilder_ == null
              ? networkTelemetry_
              : networkTelemetryBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof schemas.v1.telemetry.Telemetry.DeviceTelemetry) {
          return mergeFrom((schemas.v1.telemetry.Telemetry.DeviceTelemetry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(schemas.v1.telemetry.Telemetry.DeviceTelemetry other) {
        if (other == schemas.v1.telemetry.Telemetry.DeviceTelemetry.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getUptime() != 0L) {
          setUptime(other.getUptime());
        }
        if (java.lang.Float.floatToRawIntBits(other.getBatteryPercentage()) != 0) {
          setBatteryPercentage(other.getBatteryPercentage());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getCpuUsage()) != 0) {
          setCpuUsage(other.getCpuUsage());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getMemoryUsage()) != 0) {
          setMemoryUsage(other.getMemoryUsage());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getDiskUsage()) != 0) {
          setDiskUsage(other.getDiskUsage());
        }
        if (other.hasNetworkTelemetry()) {
          mergeNetworkTelemetry(other.getNetworkTelemetry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                uptime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 29: {
                batteryPercentage_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              case 33: {
                cpuUsage_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                memoryUsage_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                diskUsage_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 58: {
                input.readMessage(
                    internalGetNetworkTelemetryFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long uptime_ ;
      /**
       * <code>int64 uptime = 2;</code>
       * @return The uptime.
       */
      @java.lang.Override
      public long getUptime() {
        return uptime_;
      }
      /**
       * <code>int64 uptime = 2;</code>
       * @param value The uptime to set.
       * @return This builder for chaining.
       */
      public Builder setUptime(long value) {

        uptime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uptime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUptime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uptime_ = 0L;
        onChanged();
        return this;
      }

      private float batteryPercentage_ ;
      /**
       * <code>float battery_percentage = 3;</code>
       * @return The batteryPercentage.
       */
      @java.lang.Override
      public float getBatteryPercentage() {
        return batteryPercentage_;
      }
      /**
       * <code>float battery_percentage = 3;</code>
       * @param value The batteryPercentage to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryPercentage(float value) {

        batteryPercentage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float battery_percentage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryPercentage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batteryPercentage_ = 0F;
        onChanged();
        return this;
      }

      private double cpuUsage_ ;
      /**
       * <code>double cpu_usage = 4;</code>
       * @return The cpuUsage.
       */
      @java.lang.Override
      public double getCpuUsage() {
        return cpuUsage_;
      }
      /**
       * <code>double cpu_usage = 4;</code>
       * @param value The cpuUsage to set.
       * @return This builder for chaining.
       */
      public Builder setCpuUsage(double value) {

        cpuUsage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double cpu_usage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuUsage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cpuUsage_ = 0D;
        onChanged();
        return this;
      }

      private double memoryUsage_ ;
      /**
       * <code>double memory_usage = 5;</code>
       * @return The memoryUsage.
       */
      @java.lang.Override
      public double getMemoryUsage() {
        return memoryUsage_;
      }
      /**
       * <code>double memory_usage = 5;</code>
       * @param value The memoryUsage to set.
       * @return This builder for chaining.
       */
      public Builder setMemoryUsage(double value) {

        memoryUsage_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double memory_usage = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemoryUsage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        memoryUsage_ = 0D;
        onChanged();
        return this;
      }

      private double diskUsage_ ;
      /**
       * <code>double disk_usage = 6;</code>
       * @return The diskUsage.
       */
      @java.lang.Override
      public double getDiskUsage() {
        return diskUsage_;
      }
      /**
       * <code>double disk_usage = 6;</code>
       * @param value The diskUsage to set.
       * @return This builder for chaining.
       */
      public Builder setDiskUsage(double value) {

        diskUsage_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double disk_usage = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiskUsage() {
        bitField0_ = (bitField0_ & ~0x00000020);
        diskUsage_ = 0D;
        onChanged();
        return this;
      }

      private schemas.v1.telemetry.Telemetry.NetworkTelemetry networkTelemetry_;
      private com.google.protobuf.SingleFieldBuilder<
          schemas.v1.telemetry.Telemetry.NetworkTelemetry, schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder, schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder> networkTelemetryBuilder_;
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       * @return Whether the networkTelemetry field is set.
       */
      public boolean hasNetworkTelemetry() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       * @return The networkTelemetry.
       */
      public schemas.v1.telemetry.Telemetry.NetworkTelemetry getNetworkTelemetry() {
        if (networkTelemetryBuilder_ == null) {
          return networkTelemetry_ == null ? schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance() : networkTelemetry_;
        } else {
          return networkTelemetryBuilder_.getMessage();
        }
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public Builder setNetworkTelemetry(schemas.v1.telemetry.Telemetry.NetworkTelemetry value) {
        if (networkTelemetryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          networkTelemetry_ = value;
        } else {
          networkTelemetryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public Builder setNetworkTelemetry(
          schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder builderForValue) {
        if (networkTelemetryBuilder_ == null) {
          networkTelemetry_ = builderForValue.build();
        } else {
          networkTelemetryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public Builder mergeNetworkTelemetry(schemas.v1.telemetry.Telemetry.NetworkTelemetry value) {
        if (networkTelemetryBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            networkTelemetry_ != null &&
            networkTelemetry_ != schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance()) {
            getNetworkTelemetryBuilder().mergeFrom(value);
          } else {
            networkTelemetry_ = value;
          }
        } else {
          networkTelemetryBuilder_.mergeFrom(value);
        }
        if (networkTelemetry_ != null) {
          bitField0_ |= 0x00000040;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public Builder clearNetworkTelemetry() {
        bitField0_ = (bitField0_ & ~0x00000040);
        networkTelemetry_ = null;
        if (networkTelemetryBuilder_ != null) {
          networkTelemetryBuilder_.dispose();
          networkTelemetryBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder getNetworkTelemetryBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return internalGetNetworkTelemetryFieldBuilder().getBuilder();
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      public schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder getNetworkTelemetryOrBuilder() {
        if (networkTelemetryBuilder_ != null) {
          return networkTelemetryBuilder_.getMessageOrBuilder();
        } else {
          return networkTelemetry_ == null ?
              schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance() : networkTelemetry_;
        }
      }
      /**
       * <code>.schemas.v1.telemetry.NetworkTelemetry network_telemetry = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          schemas.v1.telemetry.Telemetry.NetworkTelemetry, schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder, schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder> 
          internalGetNetworkTelemetryFieldBuilder() {
        if (networkTelemetryBuilder_ == null) {
          networkTelemetryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              schemas.v1.telemetry.Telemetry.NetworkTelemetry, schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder, schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder>(
                  getNetworkTelemetry(),
                  getParentForChildren(),
                  isClean());
          networkTelemetry_ = null;
        }
        return networkTelemetryBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:schemas.v1.telemetry.DeviceTelemetry)
    }

    // @@protoc_insertion_point(class_scope:schemas.v1.telemetry.DeviceTelemetry)
    private static final schemas.v1.telemetry.Telemetry.DeviceTelemetry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new schemas.v1.telemetry.Telemetry.DeviceTelemetry();
    }

    public static schemas.v1.telemetry.Telemetry.DeviceTelemetry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceTelemetry>
        PARSER = new com.google.protobuf.AbstractParser<DeviceTelemetry>() {
      @java.lang.Override
      public DeviceTelemetry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DeviceTelemetry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceTelemetry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public schemas.v1.telemetry.Telemetry.DeviceTelemetry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NetworkTelemetryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schemas.v1.telemetry.NetworkTelemetry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string network_type = 1;</code>
     * @return The networkType.
     */
    java.lang.String getNetworkType();
    /**
     * <code>string network_type = 1;</code>
     * @return The bytes for networkType.
     */
    com.google.protobuf.ByteString
        getNetworkTypeBytes();

    /**
     * <code>string mobile_country_code = 2;</code>
     * @return The mobileCountryCode.
     */
    java.lang.String getMobileCountryCode();
    /**
     * <code>string mobile_country_code = 2;</code>
     * @return The bytes for mobileCountryCode.
     */
    com.google.protobuf.ByteString
        getMobileCountryCodeBytes();

    /**
     * <code>string mobile_network_code = 3;</code>
     * @return The mobileNetworkCode.
     */
    java.lang.String getMobileNetworkCode();
    /**
     * <code>string mobile_network_code = 3;</code>
     * @return The bytes for mobileNetworkCode.
     */
    com.google.protobuf.ByteString
        getMobileNetworkCodeBytes();

    /**
     * <code>string cell_id = 4;</code>
     * @return The cellId.
     */
    java.lang.String getCellId();
    /**
     * <code>string cell_id = 4;</code>
     * @return The bytes for cellId.
     */
    com.google.protobuf.ByteString
        getCellIdBytes();

    /**
     * <code>int32 signal_strength = 5;</code>
     * @return The signalStrength.
     */
    int getSignalStrength();
  }
  /**
   * Protobuf type {@code schemas.v1.telemetry.NetworkTelemetry}
   */
  public static final class NetworkTelemetry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:schemas.v1.telemetry.NetworkTelemetry)
      NetworkTelemetryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        NetworkTelemetry.class.getName());
    }
    // Use NetworkTelemetry.newBuilder() to construct.
    private NetworkTelemetry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetworkTelemetry() {
      networkType_ = "";
      mobileCountryCode_ = "";
      mobileNetworkCode_ = "";
      cellId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_NetworkTelemetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schemas.v1.telemetry.Telemetry.NetworkTelemetry.class, schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder.class);
    }

    public static final int NETWORK_TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object networkType_ = "";
    /**
     * <code>string network_type = 1;</code>
     * @return The networkType.
     */
    @java.lang.Override
    public java.lang.String getNetworkType() {
      java.lang.Object ref = networkType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        networkType_ = s;
        return s;
      }
    }
    /**
     * <code>string network_type = 1;</code>
     * @return The bytes for networkType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNetworkTypeBytes() {
      java.lang.Object ref = networkType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        networkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_COUNTRY_CODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mobileCountryCode_ = "";
    /**
     * <code>string mobile_country_code = 2;</code>
     * @return The mobileCountryCode.
     */
    @java.lang.Override
    public java.lang.String getMobileCountryCode() {
      java.lang.Object ref = mobileCountryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobileCountryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile_country_code = 2;</code>
     * @return The bytes for mobileCountryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobileCountryCodeBytes() {
      java.lang.Object ref = mobileCountryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobileCountryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_NETWORK_CODE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mobileNetworkCode_ = "";
    /**
     * <code>string mobile_network_code = 3;</code>
     * @return The mobileNetworkCode.
     */
    @java.lang.Override
    public java.lang.String getMobileNetworkCode() {
      java.lang.Object ref = mobileNetworkCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobileNetworkCode_ = s;
        return s;
      }
    }
    /**
     * <code>string mobile_network_code = 3;</code>
     * @return The bytes for mobileNetworkCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobileNetworkCodeBytes() {
      java.lang.Object ref = mobileNetworkCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobileNetworkCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELL_ID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cellId_ = "";
    /**
     * <code>string cell_id = 4;</code>
     * @return The cellId.
     */
    @java.lang.Override
    public java.lang.String getCellId() {
      java.lang.Object ref = cellId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cellId_ = s;
        return s;
      }
    }
    /**
     * <code>string cell_id = 4;</code>
     * @return The bytes for cellId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCellIdBytes() {
      java.lang.Object ref = cellId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cellId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNAL_STRENGTH_FIELD_NUMBER = 5;
    private int signalStrength_ = 0;
    /**
     * <code>int32 signal_strength = 5;</code>
     * @return The signalStrength.
     */
    @java.lang.Override
    public int getSignalStrength() {
      return signalStrength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, networkType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mobileCountryCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, mobileCountryCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mobileNetworkCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, mobileNetworkCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cellId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, cellId_);
      }
      if (signalStrength_ != 0) {
        output.writeInt32(5, signalStrength_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(networkType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, networkType_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mobileCountryCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, mobileCountryCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mobileNetworkCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, mobileNetworkCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cellId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, cellId_);
      }
      if (signalStrength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, signalStrength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof schemas.v1.telemetry.Telemetry.NetworkTelemetry)) {
        return super.equals(obj);
      }
      schemas.v1.telemetry.Telemetry.NetworkTelemetry other = (schemas.v1.telemetry.Telemetry.NetworkTelemetry) obj;

      if (!getNetworkType()
          .equals(other.getNetworkType())) return false;
      if (!getMobileCountryCode()
          .equals(other.getMobileCountryCode())) return false;
      if (!getMobileNetworkCode()
          .equals(other.getMobileNetworkCode())) return false;
      if (!getCellId()
          .equals(other.getCellId())) return false;
      if (getSignalStrength()
          != other.getSignalStrength()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NETWORK_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkType().hashCode();
      hash = (37 * hash) + MOBILE_COUNTRY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getMobileCountryCode().hashCode();
      hash = (37 * hash) + MOBILE_NETWORK_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getMobileNetworkCode().hashCode();
      hash = (37 * hash) + CELL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCellId().hashCode();
      hash = (37 * hash) + SIGNAL_STRENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getSignalStrength();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(schemas.v1.telemetry.Telemetry.NetworkTelemetry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code schemas.v1.telemetry.NetworkTelemetry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:schemas.v1.telemetry.NetworkTelemetry)
        schemas.v1.telemetry.Telemetry.NetworkTelemetryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_NetworkTelemetry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                schemas.v1.telemetry.Telemetry.NetworkTelemetry.class, schemas.v1.telemetry.Telemetry.NetworkTelemetry.Builder.class);
      }

      // Construct using schemas.v1.telemetry.Telemetry.NetworkTelemetry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        networkType_ = "";
        mobileCountryCode_ = "";
        mobileNetworkCode_ = "";
        cellId_ = "";
        signalStrength_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return schemas.v1.telemetry.Telemetry.internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor;
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.NetworkTelemetry getDefaultInstanceForType() {
        return schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance();
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.NetworkTelemetry build() {
        schemas.v1.telemetry.Telemetry.NetworkTelemetry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public schemas.v1.telemetry.Telemetry.NetworkTelemetry buildPartial() {
        schemas.v1.telemetry.Telemetry.NetworkTelemetry result = new schemas.v1.telemetry.Telemetry.NetworkTelemetry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(schemas.v1.telemetry.Telemetry.NetworkTelemetry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.networkType_ = networkType_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mobileCountryCode_ = mobileCountryCode_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mobileNetworkCode_ = mobileNetworkCode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.cellId_ = cellId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.signalStrength_ = signalStrength_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof schemas.v1.telemetry.Telemetry.NetworkTelemetry) {
          return mergeFrom((schemas.v1.telemetry.Telemetry.NetworkTelemetry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(schemas.v1.telemetry.Telemetry.NetworkTelemetry other) {
        if (other == schemas.v1.telemetry.Telemetry.NetworkTelemetry.getDefaultInstance()) return this;
        if (!other.getNetworkType().isEmpty()) {
          networkType_ = other.networkType_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMobileCountryCode().isEmpty()) {
          mobileCountryCode_ = other.mobileCountryCode_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMobileNetworkCode().isEmpty()) {
          mobileNetworkCode_ = other.mobileNetworkCode_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getCellId().isEmpty()) {
          cellId_ = other.cellId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getSignalStrength() != 0) {
          setSignalStrength(other.getSignalStrength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                networkType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mobileCountryCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                mobileNetworkCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                cellId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                signalStrength_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object networkType_ = "";
      /**
       * <code>string network_type = 1;</code>
       * @return The networkType.
       */
      public java.lang.String getNetworkType() {
        java.lang.Object ref = networkType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          networkType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string network_type = 1;</code>
       * @return The bytes for networkType.
       */
      public com.google.protobuf.ByteString
          getNetworkTypeBytes() {
        java.lang.Object ref = networkType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          networkType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string network_type = 1;</code>
       * @param value The networkType to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        networkType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string network_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetworkType() {
        networkType_ = getDefaultInstance().getNetworkType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string network_type = 1;</code>
       * @param value The bytes for networkType to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        networkType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object mobileCountryCode_ = "";
      /**
       * <code>string mobile_country_code = 2;</code>
       * @return The mobileCountryCode.
       */
      public java.lang.String getMobileCountryCode() {
        java.lang.Object ref = mobileCountryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobileCountryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile_country_code = 2;</code>
       * @return The bytes for mobileCountryCode.
       */
      public com.google.protobuf.ByteString
          getMobileCountryCodeBytes() {
        java.lang.Object ref = mobileCountryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobileCountryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile_country_code = 2;</code>
       * @param value The mobileCountryCode to set.
       * @return This builder for chaining.
       */
      public Builder setMobileCountryCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mobileCountryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile_country_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileCountryCode() {
        mobileCountryCode_ = getDefaultInstance().getMobileCountryCode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string mobile_country_code = 2;</code>
       * @param value The bytes for mobileCountryCode to set.
       * @return This builder for chaining.
       */
      public Builder setMobileCountryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mobileCountryCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object mobileNetworkCode_ = "";
      /**
       * <code>string mobile_network_code = 3;</code>
       * @return The mobileNetworkCode.
       */
      public java.lang.String getMobileNetworkCode() {
        java.lang.Object ref = mobileNetworkCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobileNetworkCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobile_network_code = 3;</code>
       * @return The bytes for mobileNetworkCode.
       */
      public com.google.protobuf.ByteString
          getMobileNetworkCodeBytes() {
        java.lang.Object ref = mobileNetworkCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobileNetworkCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobile_network_code = 3;</code>
       * @param value The mobileNetworkCode to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNetworkCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mobileNetworkCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string mobile_network_code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileNetworkCode() {
        mobileNetworkCode_ = getDefaultInstance().getMobileNetworkCode();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string mobile_network_code = 3;</code>
       * @param value The bytes for mobileNetworkCode to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNetworkCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mobileNetworkCode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object cellId_ = "";
      /**
       * <code>string cell_id = 4;</code>
       * @return The cellId.
       */
      public java.lang.String getCellId() {
        java.lang.Object ref = cellId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cellId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cell_id = 4;</code>
       * @return The bytes for cellId.
       */
      public com.google.protobuf.ByteString
          getCellIdBytes() {
        java.lang.Object ref = cellId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cellId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cell_id = 4;</code>
       * @param value The cellId to set.
       * @return This builder for chaining.
       */
      public Builder setCellId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cellId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string cell_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCellId() {
        cellId_ = getDefaultInstance().getCellId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string cell_id = 4;</code>
       * @param value The bytes for cellId to set.
       * @return This builder for chaining.
       */
      public Builder setCellIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cellId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int signalStrength_ ;
      /**
       * <code>int32 signal_strength = 5;</code>
       * @return The signalStrength.
       */
      @java.lang.Override
      public int getSignalStrength() {
        return signalStrength_;
      }
      /**
       * <code>int32 signal_strength = 5;</code>
       * @param value The signalStrength to set.
       * @return This builder for chaining.
       */
      public Builder setSignalStrength(int value) {

        signalStrength_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 signal_strength = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignalStrength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        signalStrength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schemas.v1.telemetry.NetworkTelemetry)
    }

    // @@protoc_insertion_point(class_scope:schemas.v1.telemetry.NetworkTelemetry)
    private static final schemas.v1.telemetry.Telemetry.NetworkTelemetry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new schemas.v1.telemetry.Telemetry.NetworkTelemetry();
    }

    public static schemas.v1.telemetry.Telemetry.NetworkTelemetry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetworkTelemetry>
        PARSER = new com.google.protobuf.AbstractParser<NetworkTelemetry>() {
      @java.lang.Override
      public NetworkTelemetry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetworkTelemetry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetworkTelemetry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public schemas.v1.telemetry.Telemetry.NetworkTelemetry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_schemas_v1_telemetry_DeviceTelemetry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_schemas_v1_telemetry_NetworkTelemetry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'vehicle-tracker-schemas/Telemetry.prot" +
      "o\022\024schemas.v1.telemetry\"\320\001\n\017DeviceTeleme" +
      "try\022\021\n\ttimestamp\030\001 \001(\003\022\016\n\006uptime\030\002 \001(\003\022\032" +
      "\n\022battery_percentage\030\003 \001(\002\022\021\n\tcpu_usage\030" +
      "\004 \001(\001\022\024\n\014memory_usage\030\005 \001(\001\022\022\n\ndisk_usag" +
      "e\030\006 \001(\001\022A\n\021network_telemetry\030\007 \001(\0132&.sch" +
      "emas.v1.telemetry.NetworkTelemetry\"\214\001\n\020N" +
      "etworkTelemetry\022\024\n\014network_type\030\001 \001(\t\022\033\n" +
      "\023mobile_country_code\030\002 \001(\t\022\033\n\023mobile_net" +
      "work_code\030\003 \001(\t\022\017\n\007cell_id\030\004 \001(\t\022\027\n\017sign" +
      "al_strength\030\005 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schemas_v1_telemetry_DeviceTelemetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_schemas_v1_telemetry_DeviceTelemetry_descriptor,
        new java.lang.String[] { "Timestamp", "Uptime", "BatteryPercentage", "CpuUsage", "MemoryUsage", "DiskUsage", "NetworkTelemetry", });
    internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schemas_v1_telemetry_NetworkTelemetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_schemas_v1_telemetry_NetworkTelemetry_descriptor,
        new java.lang.String[] { "NetworkType", "MobileCountryCode", "MobileNetworkCode", "CellId", "SignalStrength", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
