/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SCHEMAS_V1_LOCATION_VEHICLE_TRACKER_SCHEMAS_LOCATION_PB_H_INCLUDED
#define PB_SCHEMAS_V1_LOCATION_VEHICLE_TRACKER_SCHEMAS_LOCATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _schemas_v1_location_Location {
    int64_t timestamp;
    double latitude;
    pb_callback_t latitude_hemisphere;
    double longitude;
    pb_callback_t longitude_hemisphere;
    float altitude;
    float speed;
    float heading;
} schemas_v1_location_Location;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define schemas_v1_location_Location_init_default {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, 0}
#define schemas_v1_location_Location_init_zero   {0, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define schemas_v1_location_Location_timestamp_tag 1
#define schemas_v1_location_Location_latitude_tag 2
#define schemas_v1_location_Location_latitude_hemisphere_tag 3
#define schemas_v1_location_Location_longitude_tag 4
#define schemas_v1_location_Location_longitude_hemisphere_tag 5
#define schemas_v1_location_Location_altitude_tag 6
#define schemas_v1_location_Location_speed_tag   7
#define schemas_v1_location_Location_heading_tag 8

/* Struct field encoding specification for nanopb */
#define schemas_v1_location_Location_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         1) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          2) \
X(a, CALLBACK, SINGULAR, STRING,   latitude_hemisphere,   3) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         4) \
X(a, CALLBACK, SINGULAR, STRING,   longitude_hemisphere,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             7) \
X(a, STATIC,   SINGULAR, FLOAT,    heading,           8)
#define schemas_v1_location_Location_CALLBACK pb_default_field_callback
#define schemas_v1_location_Location_DEFAULT NULL

extern const pb_msgdesc_t schemas_v1_location_Location_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define schemas_v1_location_Location_fields &schemas_v1_location_Location_msg

/* Maximum encoded size of messages (where known) */
/* schemas_v1_location_Location_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
