/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "Location.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(schemas_v1_location_Location, schemas_v1_location_Location, AUTO)



