// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Location.proto
// Protobuf Java Version: 4.32.1

package schemas.v1.location;

@com.google.protobuf.Generated
public final class LocationOuterClass extends com.google.protobuf.GeneratedFile {
  private LocationOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      LocationOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:schemas.v1.location.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string time = 1;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 1;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>double latitude = 3;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>string latitude_hemisphere = 4;</code>
     * @return The latitudeHemisphere.
     */
    java.lang.String getLatitudeHemisphere();
    /**
     * <code>string latitude_hemisphere = 4;</code>
     * @return The bytes for latitudeHemisphere.
     */
    com.google.protobuf.ByteString
        getLatitudeHemisphereBytes();

    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>string longitude_hemisphere = 6;</code>
     * @return The longitudeHemisphere.
     */
    java.lang.String getLongitudeHemisphere();
    /**
     * <code>string longitude_hemisphere = 6;</code>
     * @return The bytes for longitudeHemisphere.
     */
    com.google.protobuf.ByteString
        getLongitudeHemisphereBytes();

    /**
     * <code>float altitude = 7;</code>
     * @return The altitude.
     */
    float getAltitude();

    /**
     * <code>float speed = 8;</code>
     * @return The speed.
     */
    float getSpeed();

    /**
     * <code>float heading = 9;</code>
     * @return The heading.
     */
    float getHeading();
  }
  /**
   * Protobuf type {@code schemas.v1.location.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:schemas.v1.location.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 1,
        /* suffix= */ "",
        Location.class.getName());
    }
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      time_ = "";
      date_ = "";
      latitudeHemisphere_ = "";
      longitudeHemisphere_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schemas.v1.location.LocationOuterClass.internal_static_schemas_v1_location_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schemas.v1.location.LocationOuterClass.internal_static_schemas_v1_location_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schemas.v1.location.LocationOuterClass.Location.class, schemas.v1.location.LocationOuterClass.Location.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object time_ = "";
    /**
     * <code>string time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 1;</code>
     * @return The bytes for time.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 3;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LATITUDE_HEMISPHERE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object latitudeHemisphere_ = "";
    /**
     * <code>string latitude_hemisphere = 4;</code>
     * @return The latitudeHemisphere.
     */
    @java.lang.Override
    public java.lang.String getLatitudeHemisphere() {
      java.lang.Object ref = latitudeHemisphere_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latitudeHemisphere_ = s;
        return s;
      }
    }
    /**
     * <code>string latitude_hemisphere = 4;</code>
     * @return The bytes for latitudeHemisphere.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLatitudeHemisphereBytes() {
      java.lang.Object ref = latitudeHemisphere_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitudeHemisphere_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int LONGITUDE_HEMISPHERE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object longitudeHemisphere_ = "";
    /**
     * <code>string longitude_hemisphere = 6;</code>
     * @return The longitudeHemisphere.
     */
    @java.lang.Override
    public java.lang.String getLongitudeHemisphere() {
      java.lang.Object ref = longitudeHemisphere_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitudeHemisphere_ = s;
        return s;
      }
    }
    /**
     * <code>string longitude_hemisphere = 6;</code>
     * @return The bytes for longitudeHemisphere.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLongitudeHemisphereBytes() {
      java.lang.Object ref = longitudeHemisphere_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitudeHemisphere_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALTITUDE_FIELD_NUMBER = 7;
    private float altitude_ = 0F;
    /**
     * <code>float altitude = 7;</code>
     * @return The altitude.
     */
    @java.lang.Override
    public float getAltitude() {
      return altitude_;
    }

    public static final int SPEED_FIELD_NUMBER = 8;
    private float speed_ = 0F;
    /**
     * <code>float speed = 8;</code>
     * @return The speed.
     */
    @java.lang.Override
    public float getSpeed() {
      return speed_;
    }

    public static final int HEADING_FIELD_NUMBER = 9;
    private float heading_ = 0F;
    /**
     * <code>float heading = 9;</code>
     * @return The heading.
     */
    @java.lang.Override
    public float getHeading() {
      return heading_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, time_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, date_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(3, latitude_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(latitudeHemisphere_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, latitudeHemisphere_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(5, longitude_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(longitudeHemisphere_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, longitudeHemisphere_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        output.writeFloat(7, altitude_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        output.writeFloat(8, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(heading_) != 0) {
        output.writeFloat(9, heading_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, time_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, date_);
      }
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(latitudeHemisphere_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, latitudeHemisphere_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, longitude_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(longitudeHemisphere_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, longitudeHemisphere_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, altitude_);
      }
      if (java.lang.Float.floatToRawIntBits(speed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, speed_);
      }
      if (java.lang.Float.floatToRawIntBits(heading_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, heading_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof schemas.v1.location.LocationOuterClass.Location)) {
        return super.equals(obj);
      }
      schemas.v1.location.LocationOuterClass.Location other = (schemas.v1.location.LocationOuterClass.Location) obj;

      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (!getLatitudeHemisphere()
          .equals(other.getLatitudeHemisphere())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!getLongitudeHemisphere()
          .equals(other.getLongitudeHemisphere())) return false;
      if (java.lang.Float.floatToIntBits(getAltitude())
          != java.lang.Float.floatToIntBits(
              other.getAltitude())) return false;
      if (java.lang.Float.floatToIntBits(getSpeed())
          != java.lang.Float.floatToIntBits(
              other.getSpeed())) return false;
      if (java.lang.Float.floatToIntBits(getHeading())
          != java.lang.Float.floatToIntBits(
              other.getHeading())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LATITUDE_HEMISPHERE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitudeHemisphere().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LONGITUDE_HEMISPHERE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitudeHemisphere().hashCode();
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAltitude());
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeed());
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHeading());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static schemas.v1.location.LocationOuterClass.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static schemas.v1.location.LocationOuterClass.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static schemas.v1.location.LocationOuterClass.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(schemas.v1.location.LocationOuterClass.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code schemas.v1.location.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:schemas.v1.location.Location)
        schemas.v1.location.LocationOuterClass.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return schemas.v1.location.LocationOuterClass.internal_static_schemas_v1_location_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return schemas.v1.location.LocationOuterClass.internal_static_schemas_v1_location_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                schemas.v1.location.LocationOuterClass.Location.class, schemas.v1.location.LocationOuterClass.Location.Builder.class);
      }

      // Construct using schemas.v1.location.LocationOuterClass.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        time_ = "";
        date_ = "";
        latitude_ = 0D;
        latitudeHemisphere_ = "";
        longitude_ = 0D;
        longitudeHemisphere_ = "";
        altitude_ = 0F;
        speed_ = 0F;
        heading_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return schemas.v1.location.LocationOuterClass.internal_static_schemas_v1_location_Location_descriptor;
      }

      @java.lang.Override
      public schemas.v1.location.LocationOuterClass.Location getDefaultInstanceForType() {
        return schemas.v1.location.LocationOuterClass.Location.getDefaultInstance();
      }

      @java.lang.Override
      public schemas.v1.location.LocationOuterClass.Location build() {
        schemas.v1.location.LocationOuterClass.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public schemas.v1.location.LocationOuterClass.Location buildPartial() {
        schemas.v1.location.LocationOuterClass.Location result = new schemas.v1.location.LocationOuterClass.Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(schemas.v1.location.LocationOuterClass.Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.time_ = time_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.date_ = date_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.latitudeHemisphere_ = latitudeHemisphere_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.longitude_ = longitude_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.longitudeHemisphere_ = longitudeHemisphere_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.altitude_ = altitude_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.heading_ = heading_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof schemas.v1.location.LocationOuterClass.Location) {
          return mergeFrom((schemas.v1.location.LocationOuterClass.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(schemas.v1.location.LocationOuterClass.Location other) {
        if (other == schemas.v1.location.LocationOuterClass.Location.getDefaultInstance()) return this;
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getLatitude()) != 0) {
          setLatitude(other.getLatitude());
        }
        if (!other.getLatitudeHemisphere().isEmpty()) {
          latitudeHemisphere_ = other.latitudeHemisphere_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getLongitude()) != 0) {
          setLongitude(other.getLongitude());
        }
        if (!other.getLongitudeHemisphere().isEmpty()) {
          longitudeHemisphere_ = other.longitudeHemisphere_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (java.lang.Float.floatToRawIntBits(other.getAltitude()) != 0) {
          setAltitude(other.getAltitude());
        }
        if (java.lang.Float.floatToRawIntBits(other.getSpeed()) != 0) {
          setSpeed(other.getSpeed());
        }
        if (java.lang.Float.floatToRawIntBits(other.getHeading()) != 0) {
          setHeading(other.getHeading());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                time_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 34: {
                latitudeHemisphere_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 41: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 50: {
                longitudeHemisphere_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 61: {
                altitude_ = input.readFloat();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              case 69: {
                speed_ = input.readFloat();
                bitField0_ |= 0x00000080;
                break;
              } // case 69
              case 77: {
                heading_ = input.readFloat();
                bitField0_ |= 0x00000100;
                break;
              } // case 77
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 1;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        time_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        time_ = getDefaultInstance().getTime();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string time = 1;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        time_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 2;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 3;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 3;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object latitudeHemisphere_ = "";
      /**
       * <code>string latitude_hemisphere = 4;</code>
       * @return The latitudeHemisphere.
       */
      public java.lang.String getLatitudeHemisphere() {
        java.lang.Object ref = latitudeHemisphere_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latitudeHemisphere_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string latitude_hemisphere = 4;</code>
       * @return The bytes for latitudeHemisphere.
       */
      public com.google.protobuf.ByteString
          getLatitudeHemisphereBytes() {
        java.lang.Object ref = latitudeHemisphere_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitudeHemisphere_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string latitude_hemisphere = 4;</code>
       * @param value The latitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLatitudeHemisphere(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        latitudeHemisphere_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string latitude_hemisphere = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitudeHemisphere() {
        latitudeHemisphere_ = getDefaultInstance().getLatitudeHemisphere();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string latitude_hemisphere = 4;</code>
       * @param value The bytes for latitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLatitudeHemisphereBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        latitudeHemisphere_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 5;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 5;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object longitudeHemisphere_ = "";
      /**
       * <code>string longitude_hemisphere = 6;</code>
       * @return The longitudeHemisphere.
       */
      public java.lang.String getLongitudeHemisphere() {
        java.lang.Object ref = longitudeHemisphere_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longitudeHemisphere_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string longitude_hemisphere = 6;</code>
       * @return The bytes for longitudeHemisphere.
       */
      public com.google.protobuf.ByteString
          getLongitudeHemisphereBytes() {
        java.lang.Object ref = longitudeHemisphere_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitudeHemisphere_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string longitude_hemisphere = 6;</code>
       * @param value The longitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLongitudeHemisphere(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        longitudeHemisphere_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string longitude_hemisphere = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitudeHemisphere() {
        longitudeHemisphere_ = getDefaultInstance().getLongitudeHemisphere();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string longitude_hemisphere = 6;</code>
       * @param value The bytes for longitudeHemisphere to set.
       * @return This builder for chaining.
       */
      public Builder setLongitudeHemisphereBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        longitudeHemisphere_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <code>float altitude = 7;</code>
       * @return The altitude.
       */
      @java.lang.Override
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <code>float altitude = 7;</code>
       * @param value The altitude to set.
       * @return This builder for chaining.
       */
      public Builder setAltitude(float value) {

        altitude_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>float altitude = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        altitude_ = 0F;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>float speed = 8;</code>
       * @return The speed.
       */
      @java.lang.Override
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>float speed = 8;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(float value) {

        speed_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>float speed = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000080);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private float heading_ ;
      /**
       * <code>float heading = 9;</code>
       * @return The heading.
       */
      @java.lang.Override
      public float getHeading() {
        return heading_;
      }
      /**
       * <code>float heading = 9;</code>
       * @param value The heading to set.
       * @return This builder for chaining.
       */
      public Builder setHeading(float value) {

        heading_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>float heading = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeading() {
        bitField0_ = (bitField0_ & ~0x00000100);
        heading_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:schemas.v1.location.Location)
    }

    // @@protoc_insertion_point(class_scope:schemas.v1.location.Location)
    private static final schemas.v1.location.LocationOuterClass.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new schemas.v1.location.LocationOuterClass.Location();
    }

    public static schemas.v1.location.LocationOuterClass.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public schemas.v1.location.LocationOuterClass.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schemas_v1_location_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_schemas_v1_location_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Location.proto\022\023schemas.v1.location\"\270\001" +
      "\n\010Location\022\014\n\004time\030\001 \001(\t\022\014\n\004date\030\002 \001(\t\022\020" +
      "\n\010latitude\030\003 \001(\001\022\033\n\023latitude_hemisphere\030" +
      "\004 \001(\t\022\021\n\tlongitude\030\005 \001(\001\022\034\n\024longitude_he" +
      "misphere\030\006 \001(\t\022\020\n\010altitude\030\007 \001(\002\022\r\n\005spee" +
      "d\030\010 \001(\002\022\017\n\007heading\030\t \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_schemas_v1_location_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schemas_v1_location_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_schemas_v1_location_Location_descriptor,
        new java.lang.String[] { "Time", "Date", "Latitude", "LatitudeHemisphere", "Longitude", "LongitudeHemisphere", "Altitude", "Speed", "Heading", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
