name: Docker Build

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingestion-service, asset-service, api-gateway]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.service }} image
        working-directory: vehicle-tracker-backend/${{ matrix.service }}/container
        run: ./buildContainer.sh
